export const countries = [
  { code: "IN", name: "India" },
  { code: "CN", name: "China" },
  { code: "US", name: "United States" },
  { code: "ID", name: "Indonesia" },
  { code: "PK", name: "Pakistan" },
  { code: "NG", name: "Nigeria" },
  { code: "BR", name: "Brazil" },
  { code: "BD", name: "Bangladesh" },
  { code: "RU", name: "Russia" },
  { code: "MX", name: "Mexico" },
  { code: "JP", name: "Japan" },
  { code: "ET", name: "Ethiopia" },
  { code: "PH", name: "Philippines" },
  { code: "EG", name: "Egypt" },
  { code: "VN", name: "Vietnam" },
  { code: "CD", name: "Democratic Republic of the Congo" },
  { code: "TR", name: "Turkey" },
  { code: "IR", name: "Iran" },
  { code: "DE", name: "Germany" },
  { code: "TH", name: "Thailand" },
  { code: "GB", name: "United Kingdom" },
  { code: "FR", name: "France" },
  { code: "IT", name: "Italy" },
  { code: "TZ", name: "Tanzania" },
  { code: "ZA", name: "South Africa" },
  { code: "MM", name: "Myanmar" },
  { code: "KE", name: "Kenya" },
  { code: "KR", name: "South Korea" },
  { code: "CO", name: "Colombia" },
  { code: "ES", name: "Spain" }
]
