import './styles.css';
import { Poppins, Roboto } from 'next/font/google';
import Header from '@user-ui/src/components/Header';
import { ThemeProvider } from '@ui/index';
import Providers from '../components/providers';
import { Toaster } from 'sonner';

export const metadata = {
  title: 'Multi vendor ecom',
  description: 'Generated by create-nx-workspace',
};

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-roboto',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.variable} ${poppins.variable} min-h-screen bg-background text-foreground`}
      >
        
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <Toaster />
            <Header />
            {children}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
