import './styles.css';
import { Poppins, Roboto} from 'next/font/google';
import { Nunito, Amarna, Saira, Comfortaa, Kanit, Quicksand, Raleway, Orbitron } from "next/font/google";
import Header from '@seller-ui/src/components/Header';
import { ThemeProvider } from '@ui/index';
import Providers from '@seller-ui/src/components/providers';
import { Toaster } from 'sonner';

export const metadata = {
  title: 'Agri-Grocer',
  description: 'Generated by create-nx-workspace',
};

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-roboto',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
});


const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const amarna = Amarna({
  variable: "--font-amarna",
  subsets: ["latin"],
  adjustFontFallback: false, 
});

const saira = Saira({
  variable: "--font-saira",
  subsets: ["latin"],
});

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

const kanit = Kanit({
  variable: "--font-kanit",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800",],
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800",],
});


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.variable} ${poppins.variable}
          ${nunito.variable}
          ${amarna.variable}
          ${kanit.variable}
          ${comfortaa.variable}
          ${quicksand.variable}
          ${raleway.variable}
          ${saira.variable}
          ${orbitron.variable}
          min-h-screen bg-background text-foreground font-amarna`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <Toaster />
            {/* <Header /> */}
            {children}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
